# Generated by Django 4.2.11 on 2024-04-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookstore_app.author",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
