# Generated by Django 4.2.11 on 2024-04-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore_app", "0002_author_birth_date_alter_book_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
